# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Software (Language) Engineering Lab, East Carolina University
email: ecu.sle.lab@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is the homepage for the ECU Software (Language) Engineering lab, which focuses
  on topics in software engineering and software language engineering. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ecu-sle-lab.github.io/" # the base hostname & protocol for your site
twitter_username: hillsma
github_username:  ecu-sle-lab

# Build settings
markdown: kramdown
